package javaython;

enum TokenType {
    LEFT_PAREN, RIGHT_PAREN,
    PLUS, MINUS, STAR, SLASH,
    COLON, COMMA,
    EQUAL, EQUAL_EQUAL,
    BANG_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,
    IDENTIFIER, STRING, NUMBER,
    NEWLINE, INDENT, DEDENT, EOF,
    IF, ELIF, ELSE, WHILE, FOR, IN,
    TRUE, FALSE,
    AND, OR, NOT
}
