package javaython;

enum TokenType {
    LEFT_PAREN, RIGHT_PAREN,
    LEFT_BRACKET, RIGHT_BRACKET,
    LEFT_BRACE, RIGHT_BRACE,
    PLUS, MINUS, STAR, SLASH, FLOOR_SLASH, PERCENT,
    PLUS_EQUAL, MINUS_EQUAL, STAR_EQUAL, SLASH_EQUAL, FLOOR_SLASH_EQUAL, PERCENT_EQUAL,
    AMPERSAND, PIPE, CARET, TILDE,
    LEFT_SHIFT, RIGHT_SHIFT,
    AMPERSAND_EQUAL, PIPE_EQUAL, CARET_EQUAL, LEFT_SHIFT_EQUAL, RIGHT_SHIFT_EQUAL,
    COLON, COMMA, DOT,
    EQUAL, EQUAL_EQUAL,
    BANG_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,
    IDENTIFIER, STRING, NUMBER,
    NEWLINE, INDENT, DEDENT, EOF,
    IF, ELIF, ELSE, WHILE, FOR, IN,
    TRUE, FALSE,
    AND, OR, NOT
}
